Add nr1-cambio
newrelic/opensource-website pull request #690
Opened 2021-02-15 22:47 UTC by YeisonGaona

## chore(nr1-cambio): Added app nr1-cambio

2021-02-15 22:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/opensource-website?pullRequest=690) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/opensource-website?pullRequest=690) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/opensource-website?pullRequest=690) it.</sub>

2021-02-27 00:54 UTC, jpvajda commented
@YeisonGaona do you mind providing a screen shot of this rendering locally, so we can validate how the page looks?

2021-02-27 00:55 UTC, jpvajda reviewed
please provide the screenshot of the local render of this page. - thanks!

2021-03-01 17:09 UTC, YeisonGaona commented
> please provide the screenshot of the local render of this page. - thanks!

@jpvajda This is the screenshot. I found a problem with some capitalization, but corrected it with a third commit.

![image](https://user-images.githubusercontent.com/21069727/109532025-a6f1c180-7a86-11eb-8019-5da62611411c.png)

2021-03-01 21:41 UTC, jpvajda requested changes

2021-03-01 21:41 UTC, jpvajda commented on src/data/project-main-content/globalsoftWigilabs-nr1-cambio.mdx
> +<!--
Can you remove this commented code?

2021-03-01 21:53 UTC, YeisonGaona commented on src/data/project-main-content/globalsoftWigilabs-nr1-cambio.mdx
> +<!--
> Can you remove this commented code?

It's done

2021-03-01 21:57 UTC, jpvajda commented on src/data/projects/globalsoftWigilabs-nr1-cambio.json
> +  }
```suggestion
  }
  
```

2021-03-01 21:58 UTC, jpvajda approved these changes

2021-03-01 21:58 UTC, jpvajda commented on src/data/projects/globalsoftWigilabs-nr1-cambio.json
> +  }
added a new line to remove the no line at end of file marker

2021-03-01 23:52 UTC, jpvajda commented
@YeisonGaona there is actually one more change here, in order for this to automatically bump our release version you'll need to use conventional commits, can you go and change your most recent commit message following this format:

https://github.com/newrelic/opensource-website/blob/develop/.github/pull_request_template.md

I recommend using git rebase -i 

https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

2021-03-01 23:53 UTC, jpvajda reviewed
needs a conventional commit message.

2021-03-02 19:15 UTC, YeisonGaona commented
> needs a conventional commit message.

It's done @jpvajda

2021-03-02 20:08 UTC, jpvajda commented
@YeisonGaona Thank you so much for working through this review with me and contributing! 🥳

2021-03-02 20:08 UTC, merged

2021-03-02 20:17 UTC, YeisonGaona commented
Thanks @jpvajda for you time !