chore(categories): add images with solid white background
newrelic/opensource-website pull request #816
Opened 2021-07-24 02:54 UTC by jbeveland27

Our snippets for referencing the category images come from [this repo's wiki](https://github.com/newrelic/opensource-website/wiki/Open-Source-Category-Snippets) and reference these images. 

@brammerl was kind enough to update the images and add a white background, and added those to the open-source-office repo in [this PR](https://github.com/newrelic/open-source-office/pull/47). However we need them updated in this repo as well. This PR should take care of fixing these headers across all of the org repos.

2021-07-26 16:19 UTC, jpvajda commented
I noticed community plus file as a deletion, `BIN -1.24 KB (98%) src/images/categories/Community_Plus.png` did that get removed?

https://opensource.newrelic.com/oss-category/#community-plus

2021-07-26 16:19 UTC, jpvajda requested changes
see comment clarifying why the community plus image was deleted.

2021-07-26 18:23 UTC, zstix approved these changes

2021-07-27 18:22 UTC, jpvajda approved these changes

2021-07-27 18:22 UTC, merged