fix: Search input no longer sets darkMode to undefined
newrelic/opensource-website pull request #998
Opened 2023-05-18 23:06 UTC by tabathadelane

Use-dark-mode was setting a default darkMode key in localStorage and overriding it to undefined when the search input was used breaking the page. This seems to resolve that from what I could tell.

2023-05-19 14:34 UTC, sunnyzanchi requested changes

2023-05-19 14:34 UTC, sunnyzanchi commented on src/components/withDarkMode.js
> +      return useDarkMode(isDarkDefault, { storageProvider: false });
this breaks a rule of hooks, [hooks shouldn't be called conditionally](https://legacy.reactjs.org/docs/hooks-rules.html). you could try calling this hook above the conditional, store the result in variable, and if we hit this branch just return that result. not sure how that would interact with the value in localStorage though

2023-05-22 18:20 UTC, LizBaker approved these changes

2023-05-22 18:40 UTC, sunnyzanchi approved these changes

2023-05-22 19:52 UTC, merged